export const school_type = ["Formal Education", "Adult Education"]

export const region = ["Macau", "Taipa", "Coloane"]

export const classLevel = ["Kindergarten", "Primary School", "Secondary school"]


export const schoolName = {
  macau: [
    "Sheng Kung Hui Escola Choi Kou (Macau)",
    "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau",
    "Escola Estrela do Mar (Rua do Padre António)",
    "Escola da Associação Geral das Mulheres de Macau",
    "Jardim de Infância Anexo à Escola Lou Hau",
    "Escola Primária Anexa à Escola Lou Hau",
    "Escola Secundária Lou Hau",
    "Escola Há Ván Châm Vui",
    "Escola Hou Kong (Pré-Primário)",
    "Escola Hou Kong (Primário)",
    "Escola Hou Kong",
    "Instituto Salesiano da Imaculada Conceição",
    "Escola Secundária Ilha Verde da Associação Comercial de Macau",
    "Escola Kao Yip (Sucursal)",
    "Escola Keang Peng (Secção Primária)",
    "Escola Kwong Tai",
    "Escola Lin Fong Pou Chai",
    "Escola Ling Nam",
    "Escola de Santa Madalena",
    "Escola dos Moradores do Bairro do Patane",
    "Escola Nossa Senhora de Fátima",
    "Colégio Perpétuo Socorro Chan Sui Ki",
    "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)",
    "Escola Secundária Pui Ching",
    "Escola Pui Tou",
    "Escola Pui Tou (Sucursal da Praia Grande)",
    "Colégio Mateus Ricci (Secundário)",
    "Escola da Sagrada Família",
    "Escola Santa Maria Mazzarello",
    "Colégio de Santa Rosa de Lima - Secção Inglesa",
    "Colégio de Santa Rosa de Lima - Secção Chinesa",
    "Escola de Santa Teresa do Menino Jesus",
    "Colégio Diocesano de São José (1)",
    "Colégio Diocesano de São José (3)",
    "Colégio Diocesano de São José (4)",
    "Colégio Diocesano de São José 5 (Secção Chinesa)",
    "Escola São Paulo",
    "Escola Tak Meng",
    "Escola Tong Nam",
    "Escola Tong Sin Tong (Diurno)",
    "Colégio Yuet Wah (Secção Chinesa)",
    "Colégio Yuet Wah (Secção Inglesa)",
    "Colégio do Sagrado Coração de Jesus",
    "Colégio do Sagrado Coração de Jesus - Secção Inglesa",
    "Escola Shá Lei Tau Cham Son",
    "Escola Concórdia para Ensino Especial",
    "Escola São João de Brito",
    "Jardim Infantil da Cáritas",
    "Escola Hói Fai",
    "Centro de Educação Infantil Santo António",
    "Escola Fukien",
    "Escola Kai Chi",
    `Jardim de Infância "D.José da Costa Nunes"`,
    `Escola Primaria Oficial Luso-Chinesa "Sir Robert Ho Tung"`,
    "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes",
    "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)",
    "Colégio Diocesano de São José 5 (Secção Inglesa)",
    "Escola Kwong Tai (Sucursal)",
    "Escola dos Moradores de Macau(Avenida da Longevidade)",
    "Escola Chong Tak de Macau",
    "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)",
    "Jardim de Infância Anexo à Escola Tong Sin Tong",
    "Escola Keang Peng( Secção Secundária)",
    "Escola Sun Wah(Bairro do Hipodromo Norte, Rua de Serenidade)",
    "Escola Pui Tou ( Sucursal da Secção Primária)",
    "Escola Luso-Chinesa Técnico-Profissional",
    "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)",
    "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau",
    "Escola Portuguesa de Macau",
    "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)",
    "Escola Tong Nam - Secundária",
    "Escola Sun Wah(Avenida do Conselheiro Borja)",
    "Escola dos Moradores de Macau(Avenida do Nordeste)",
    "Escola Cham Son de Macau",
    "Escola de Dança do Conservatório de Macau",
    "Escola Estrela do Mar(Travessa do chunambeiro)",
    "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)",
    "Escola de Música do Conservatório de Macau",
    "Escola Kao Yip",
    "Seccao Infantil e Primaria do Colegio Mateus Ricci",
    "Escola Oficial Zheng Guanying",
    "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)",
    "Escola Sao Joao de Brito - Seccao Inglesa",
    "Escola de Santa Madalena (Sucursal)",
    "Colégio Diocesano de São José (2)",
    "Colégio Diocesano de São José (6) (Secção Chinesa)",
    "Colégio Diocesano de São José (6) (Secção Inglesa)",
    "Colégio do Sagrado Coração de Jesus(Jardim de Infância)",
    "Escola Oficial da Flora",
    "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)",
    "Escola São João de Brito (Nocturno)",
    "Ensino Primário Recorrente",
    "Escola Estrela do Mar (Nocturno)",
    "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)",
    "Escola Luso-Chinesa Técnico-Profissional (Nocturno)",
    "Ensino Secundário Recorrente",
    "Escola Secundária Nocturna Xin Hua",
    "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)",
    "Escola Secundária Millennium",
    "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)",
    "Colégio Diocesano de São José (6) (Secção Nocturna)",
  ],
  taipa: [
    "Escola Dom João Paulino",
    "Escola Fong Chong da Taipa (Sucursal)",
    "Escola Cáritas de Macau",
    "Escola das Nações",
    "Escola Luso-Chinesa da Taipa",
    "Escola Secundária Pui Va",
    "Escola de Talentos Anexa à Escola Hou Kong",
    "Escola Fong Chong da Taipa",
    "Escola Secundária Sam Yuk de Macau",
    "Escola Secundária Sam Yuk de Macau (Secção Inglesa)",
    "Escola de Aplicação Anexa à Universidade de Macau",
    "Colégio Anglicano de Macau",
    "Escola Internacional de Macau",
    "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)",
    "Escola Secundária Pui Va (Secção Primária e Infantil)",
    "Secção Primària da Escola Pui Tou (Sucursal da Taipa)",

  ],
  colane: [
    "Escola de São José de Ká Hó",
    "Escola Dom Luís Versíglia",
    "Escola Oficial de Seac Pai Van",
    "Gerações - Escola Internacional",
  ],
}

export const schoolAddress = {
  "Sheng Kung Hui Escola Choi Kou (Macau)": "Rua Pedro Nolasco da Silva, no.53",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau": "Istmo de Ferreira do Amaral, no.40",
  "Escola Estrela do Mar (Rua do Padre António)": "Rua do Padre António, No. 36",
  "Escola da Associação Geral das Mulheres de Macau": "Avenida do Dr. Francisco Vieira Machado, n.362",
  "Jardim de Infância Anexo à Escola Lou Hau": "Avenida Marginal do Lam mau, no.588, Macau.",
  "Escola Primária Anexa à Escola Lou Hau": "Estrada do Repouso, no. 76A",
  "Escola Secundária Lou Hau": "Rua 2 do Bairro da Concórdia, no. 163",
  "Escola Há Ván Châm Vui": "Rua da Praia do Manduco, nos. 46-48",
  "Escola Hou Kong (Pré-Primário)": "Estrada do Repouso, Nos. 73 e 75",
  "Escola Hou Kong (Primário)": "Rua Afonso de Albuquerque, nos. 25-27",
  "Escola Hou Kong": "Estrada da Ferreira do Amaral, no.3",
  "Instituto Salesiano da Imaculada Conceição": "Rua de S. Lourenço, no.16",
  "Escola Secundária Ilha Verde da Associação Comercial de Macau": "Avenida Conselheiro Borja, no.496",
  "Escola Kao Yip (Sucursal)": "Rua do Monte, nos. 4-6",
  "Escola Keang Peng (Secção Primária)": "Rua Francisco Xavier Pereira , no.128",
  "Escola Kwong Tai": "Rua de Fai Chi Kei, Habitação Social de Fai Chi Kei",
  "Escola Lin Fong Pou Chai": "Avenida do Almirante Lacerda, anexa ao Templo Lin Fong Pou Chai",
  "Escola Ling Nam": "Estrada dos Parses, no. 1",
  "Escola de Santa Madalena": "Rua Comandante João Belo, no. 28, Fai Chi Kei",
  "Escola dos Moradores do Bairro do Patane": "Rua da Palmeira, no. 99, r/c",
  "Escola Nossa Senhora de Fátima": "Rua da Missao de Fatima no. 61",
  "Colégio Perpétuo Socorro Chan Sui Ki": "Estrada da Vitória, no.28",
  "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)": "Travessa dos Bombeiros, no. 9G",
  "Escola Secundária Pui Ching": "Avenida Horta e Costa, no.7",
  "Escola Pui Tou": "Avenida do Dr. Rodrigo Rodrigues, no.263",
  "Escola Pui Tou (Sucursal da Praia Grande)": "Avenida da Praia Grande, no.779",
  "Colégio Mateus Ricci (Secundário)": "Travessa de São Paulo, no.1A",
  "Escola da Sagrada Família": "Rua de Bráz da Rosa, no. 15",
  "Escola Santa Maria Mazzarello": "Rua da Praia do Manduco, no. 103",
  "Colégio de Santa Rosa de Lima - Secção Inglesa": "Avenida Dr. Rodrigo Rodrigues, no. 367",
  "Colégio de Santa Rosa de Lima - Secção Chinesa": "Rua de Santa Clara, no. 21",
  "Escola de Santa Teresa do Menino Jesus": "Avenida do Conselheiro Borja, no. 568",
  "Colégio Diocesano de São José (1)": "Adro de S. Lázaro, no. 13",
  "Colégio Diocesano de São José (3)": "Travessa dos Anjos, no.43",
  "Colégio Diocesano de São José (4)": "Rua da Sé, no.17",
  "Colégio Diocesano de São José 5 (Secção Chinesa)": "Rua Central de Toi San, no.253 - 353",
  "Escola São Paulo": "Rampa dos Cavaleiros, nos 12-14",
  "Escola Tak Meng": "Rua do Mercado do Bairro Iao Hon, Edificio Lok Fu San Chun, 1 andar",
  "Escola Tong Nam": "Rua do Almirante Costa Cabral, no.138",
  "Escola Tong Sin Tong (Diurno)": "Rua Camilo Pessanha, no.64",
  "Colégio Yuet Wah (Secção Chinesa)": "Estrada da Vitoria, no.18",
  "Colégio Yuet Wah (Secção Inglesa)": "Estrada da Vitoria, no.18",
  "Colégio do Sagrado Coração de Jesus": "Avenida Coronel Mesquita, no.75,Macau",
  "Colégio do Sagrado Coração de Jesus - Secção Inglesa": "Avenida Ouvidor Arriaga, no.86",
  "Escola Shá Lei Tau Cham Son": "Rua Ribeira do Patane, no. 169-S",
  "Escola Concórdia para Ensino Especial": "Rua do Asilo, Bairro da Ilha Verde, No.35",
  "Escola São João de Brito": "Rua de Pedro Coutinho, no. 118",
  "Jardim Infantil da Cáritas": "Avenida I de Maio Edf.Kam Hoi San Garden",
  "Escola Hói Fai": "Praça das Portas do Cerco, Edificio Jardim San Pou, 2 andar",
  "Centro de Educação Infantil Santo António": "Avenida Primeiro de Maio, Edifício Yu Wa r/c e 1.o andar",
  "Escola Fukien": "Rua de Lei Pou Chon, s/n",
  "Escola Kai Chi": "Rampa do Padre Vasconcelos",
  "Jardim de Infância D. José da Costa Nunes": "Avenida Sidónio Pais, s/n",
  "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung": "Estrada da Vitoria",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes": "Avenida de Sidónio Pais, s/n",
  "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)": "Estrada Ferreira do Amaral, no.6",
  "Colégio Diocesano de São José 5 (Secção Inglesa)": "Rua de Lei Pou Chon, no.320-358",
  "Escola Kwong Tai (Sucursal)": "Rua Nova Patane, no. 98, Edifício Luen San Square C.C. R/C A3",
  "Escola dos Moradores de Macau(Avenida da Longevidade)": "Avenida da Longevidade, no. 355",
  "Escola Chong Tak de Macau": "Rua dos Pescadores no. 90",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)": "Avenida do Hipódromo, nos. 222-268, Wai Long Garden",
  "Jardim de Infância Anexo à Escola Tong Sin Tong": "Rua Cidade de Santarem, No. 405, Edf Dynasty Garden, 2 andar",
  "Escola Keang Peng( Secção Secundária)": "Avenida Hipódromo, no.389",
  "Escola Sun Wah(Bairro do Hipodromo Norte, Rua de Serenidade)": "Bairro do Hipodromo Norte, Rua de Serenidade,s/n",
  "Escola Pui Tou ( Sucursal da Secção Primária)": "Rua de Formosa, No. 11",
  "Escola Luso-Chinesa Técnico-Profissional": "Rua Primeiro de Maio",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)": "Avenida de Sidónio Pais, s/n",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau": "Rua de Lai Pou Chon",
  "Escola Portuguesa de Macau": "Avenida Infante D. Henrique S/N",
  "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)": "AVENIDA DR. FRANCISCO V MACHADO,No. 266",
  "Escola Tong Nam - Secundária": "Praca Luis de Camoes, Nos. 5-7",
  "Escola Sun Wah(Avenida do Conselheiro Borja)": "Avenida do Conselheiro Borja, no.355, Ka Ying Court, 2 andar",
  "Escola dos Moradores de Macau(Avenida do Nordeste)": "Avenida do Nordeste, no.109, Edif. Nam Ou, 1 e 2 andares",
  "Escola Cham Son de Macau": "Rua Central da Areia Preta, No. 410",
  "Escola de Dança do Conservatório de Macau": "Alameda Dr. Carlos D'Assumpcao No. 335-341, Hotline Building, 3 andar - NAPE",
  "Escola Estrela do Mar(Travessa do chunambeiro)": "Travessa do chunambeiro, nos.10-12",
  "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)": "Estrada Ferreira do Amaral, no.6",
  "Escola de Música do Conservatório de Macau": "Rua de Vo Long, 35",
  "Escola Kao Yip": "Avenida Xian Xing Hai, n.º 193, Macau",
  "Seccao Infantil e Primaria do Colegio Mateus Ricci": "Praca de Luis de Camoes n. 4 e Largo da Companhia n. 15",
  "Escola Oficial Zheng Guanying": "Rua Marginal do Canal das Hortas, s/n",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)": "Rua da Tranquilidade,no. 151, Jardim Wan Keng, R/C e 1?andar-B",
  "Escola Sao Joao de Brito - Seccao Inglesa": "Rua de Pedro Coutinho, no. 118",
  "Escola de Santa Madalena (Sucursal)": "Largo da Companhia, no. 14",
  "Colégio Diocesano de São José (2)": "Rua da Prata, no. 1",
  "Colégio Diocesano de São José (6) (Secção Chinesa)": "Estrada Marginal da Ilha Verde, no.14-17",
  "Colégio Diocesano de São José (6) (Secção Inglesa)": "Estrada Marginal da Ilha Verde, no.14-17",
  "Colégio do Sagrado Coração de Jesus(Jardim de Infância)": "Rua de Francisco Xavier Pereira, nos. 114-122",
  "Escola Oficial da Flora": "Travessa do Tunel, s/n, Jardim da Flora",
  "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)": "Avenida do Dr. Francisco Vieira Machado, no. 539",
  "Escola São João de Brito (Nocturno)": "Rua de Pedro Coutinho, no. 118",
  "Ensino Primário Recorrente": "Estrada da Vitoria",
  "Escola Estrela do Mar (Nocturno)": "Rua do Padre António, No. 36",
  "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)": "Rua Pedro Nolasco da Silva, no.53",
  "Escola Luso-Chinesa Técnico-Profissional (Nocturno)": "Rua Primeiro de Maio",
  "Ensino Secundário Recorrente": "Avenida de Sidónio Pais, s/n",
  "Escola Secundária Nocturna Xin Hua": "Avenda do Conselheiro Borja no 355, Ka Ying Court, 2 andar",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)": "Avenida de Sidónio Pais, s/n",
  "Escola Secundária Millennium": "Avenida Sir Anders Ljungstedt, no. 238, China Civil Plaza, 8o., 9o. andares e 17o. andar G",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)": "Rua de Lei Pou Chon",
  "Colégio Diocesano de São José (6) (Secção Nocturna)": "Estrada Marginal da Ilha Verde, no.14-17",
  "Escola Dom João Paulino": "Avenida Carlos da Maia, s/n",
  "Escola Fong Chong da Taipa (Sucursal)": "Rua do Delegado, s/n",
  "Escola Cáritas de Macau": "Rua Cidade de Lisboa, nos. 299, 371 e 387",
  "Escola das Nações": "Rua do Minho",
  "Escola Luso-Chinesa da Taipa": "Largo Governador Tamagnini Barbosa, S/N",
  "Escola Secundária Pui Va": "Rua Dois do Ocean Garden, no. 90, Edificio Ocean Garden",
  "Escola de Talentos Anexa à Escola Hou Kong": "Rua Seng Tou",
  "Escola Fong Chong da Taipa": "Rua de Chaves, no.220",
  "Escola Secundária Sam Yuk de Macau": "Rua do Colegio, s/n",
  "Escola Secundária Sam Yuk de Macau (Secção Inglesa)": "Rua do Colegio, s/n",
  "Escola de Aplicação Anexa à Universidade de Macau": "Rua de Tai Lin BT34",
  "Colégio Anglicano de Macau": "Avenida Padre Tomás Pereira, no,109-117",
  "Escola Internacional de Macau": "Avenida Wai Long, Universidade de Ciência e Tecnologia De Macau, Bloco K",
  "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)": "Rua de Nam Keng 2a Fase do Edificio Nova taipa Garaden(Nova City) fracção D R/C do Bl VI e VIII",
  "Escola Secundária Pui Va (Secção Primária e Infantil)": "Rua do Minho no. 93",
  "Secção Primària da Escola Pui Tou (Sucursal da Taipa)": "Avenida de Kwong Tung, n.os 775-827A e Rua do Minho, n.os 325-393, Edifício Hung Fat Garden, R/C, A-G, na Taipa",
  "Escola de São José de Ká Hó": "Aldeia de Ká Hó, Estrada de Nossa Senhora, no. 1151",
  "Escola Dom Luís Versíglia": "Rua Aldeia de Ká Hó",
  "Escola Oficial de Seac Pai Van": "Lote CN6a, Avenida Vale das Borboletas, Seac Pai Van",
  "Gerações - Escola Internacional": "Aterro da Concórdia, junto à Estrada de Seac Pai Van, Lote 12a",
}

export const schoolLevel = {
  "Sheng Kung Hui Escola Choi Kou (Macau)": ["Kindergarten"],
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau": ["Primary School", "Secondary school"],
  "Escola Estrela do Mar (Rua do Padre António)": ["Kindergarten", "Primary School"],
  "Escola da Associação Geral das Mulheres de Macau": ["Kindergarten", "Primary School", "Secondary school"],
  "Jardim de Infância Anexo à Escola Lou Hau": ["Kindergarten", "Primary School"],
  "Escola Primária Anexa à Escola Lou Hau": ["Kindergarten"],
  "Escola Secundária Lou Hau": ["Primary School"],
  "Escola Há Ván Châm Vui": ["Secondary school"],
  "Escola Hou Kong (Pré-Primário)": ["Kindergarten"],
  "Escola Hou Kong (Primário)": ["Kindergarten", "Primary School"],
  "Escola Hou Kong": ["Kindergarten"],
  "Instituto Salesiano da Imaculada Conceição": ["Kindergarten", "Primary School"],
  "Escola Secundária Ilha Verde da Associação Comercial de Macau": ["Primary School", "Secondary school"],
  "Escola Kao Yip (Sucursal)": ["Primary School", "Secondary school"],
  "Escola Keang Peng (Secção Primária)": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Kwong Tai": ["Kindergarten", "Primary School"],
  "Escola Lin Fong Pou Chai": ["Kindergarten", "Primary School"],
  "Escola Ling Nam": ["Secondary school"],
  "Escola de Santa Madalena": ["Kindergarten", "Primary School"],
  "Escola dos Moradores do Bairro do Patane": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Nossa Senhora de Fátima": ["Kindergarten", "Primary School"],
  "Colégio Perpétuo Socorro Chan Sui Ki": ["Kindergarten", "Primary School"],
  "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Secundária Pui Ching": ["Primary School", "Secondary school"],
  "Escola Pui Tou": ["Kindergarten", "Primary School"],
  "Escola Pui Tou (Sucursal da Praia Grande)": ["Kindergarten", "Primary School", "Secondary school"],
  "Colégio Mateus Ricci (Secundário)": ["Secondary school"],
  "Escola da Sagrada Família": ["Kindergarten", "Primary School"],
  "Escola Santa Maria Mazzarello": ["Primary School", "Secondary school"],
  "Colégio de Santa Rosa de Lima - Secção Inglesa": ["Kindergarten", "Primary School"],
  "Colégio de Santa Rosa de Lima - Secção Chinesa": ["Kindergarten", "Primary School"],
  "Escola de Santa Teresa do Menino Jesus": ["Primary School", "Secondary school"],
  "Colégio Diocesano de São José (1)": ["Kindergarten", "Primary School", "Secondary school"],
  "Colégio Diocesano de São José (3)": ["Kindergarten", "Primary School"],
  "Colégio Diocesano de São José (4)": ["Kindergarten", "Primary School"],
  "Colégio Diocesano de São José 5 (Secção Chinesa)": ["Primary School", "Secondary school"],
  "Escola São Paulo": ["Kindergarten"],
  "Escola Tak Meng": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Tong Nam": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Tong Sin Tong (Diurno)": ["Kindergarten", "Primary School", "Secondary school"],
  "Colégio Yuet Wah (Secção Chinesa)": ["Secondary school"],
  "Colégio Yuet Wah (Secção Inglesa)": ["Kindergarten", "Primary School"],
  "Colégio do Sagrado Coração de Jesus": ["Kindergarten", "Primary School"],
  "Colégio do Sagrado Coração de Jesus - Secção Inglesa": ["Primary School", "Secondary school"],
  "Escola Shá Lei Tau Cham Son": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Concórdia para Ensino Especial": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola São João de Brito": ["Kindergarten", "Primary School", "Secondary school"],
  "Jardim Infantil da Cáritas": ["Primary School", "Secondary school"],
  "Escola Hói Fai": ["Kindergarten", "Primary School"],
  "Centro de Educação Infantil Santo António": ["Special education", "Kindergarten", "Primary School", "Secondary school"],
  "Escola Fukien": ["Primary School", "Secondary school"],
  "Escola Kai Chi": ["Primary School", "Secondary school"],
  "Jardim de Infância D. José da Costa Nunes": ["Special education", "Kindergarten", "Primary School", "Secondary school"],
  "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung": ["Kindergarten"],
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes": ["Special education", "Kindergarten", "Primary School", "Secondary school"],
  "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)": ["Kindergarten", "Primary School"],
  "Colégio Diocesano de São José 5 (Secção Inglesa)": ["Kindergarten"],
  "Escola Kwong Tai (Sucursal)": ["Kindergarten", "Primary School"],
  "Escola dos Moradores de Macau(Avenida da Longevidade)": ["Special education", "Kindergarten"],
  "Escola Chong Tak de Macau": ["Special education", "Kindergarten"],
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)": ["Special education", "Kindergarten", "Primary School"],
  "Jardim de Infância Anexo à Escola Tong Sin Tong": ["Special education", "Kindergarten", "Primary School"],
  "Escola Keang Peng( Secção Secundária)": ["Secondary school"],
  "Escola Sun Wah(Bairro do Hipodromo Norte, Rua de Serenidade)": ["Primary School"],
  "Escola Pui Tou ( Sucursal da Secção Primária)": ["Primary School", "Secondary school"],
  "Escola Luso-Chinesa Técnico-Profissional": ["Kindergarten", "Primary School"],
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)": ["Secondary school"],
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau": ["Kindergarten", "Primary School"],
  "Escola Portuguesa de Macau": ["Kindergarten", "Primary School", "Secondary school"],
  "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)": ["Kindergarten"],
  "Escola Tong Nam - Secundária": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Sun Wah(Avenida do Conselheiro Borja)": ["Kindergarten"],
  "Escola dos Moradores de Macau(Avenida do Nordeste)": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Cham Son de Macau": ["Primary School", "Secondary school"],
  "Escola de Dança do Conservatório de Macau": ["Primary School"],
  "Escola Estrela do Mar(Travessa do chunambeiro)": ["Primary School", "Secondary school"],
  "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)": ["Secondary school"],
  "Escola de Música do Conservatório de Macau": ["Secondary school"],
  "Escola Kao Yip": ["Secondary school"],
  "Seccao Infantil e Primaria do Colegio Mateus Ricci": ["Secondary school"],
  "Escola Oficial Zheng Guanying": ["Primary School"],
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Sao Joao de Brito - Seccao Inglesa": ["Special education", "Kindergarten", "Primary School", "Secondary school"],
  "Escola de Santa Madalena (Sucursal)": ["Kindergarten", "Primary School", "Secondary school"],
  "Colégio Diocesano de São José (2)": ["Kindergarten", "Primary School", "Secondary school"],
  "Colégio Diocesano de São José (6) (Secção Chinesa)": ["Primary School", "Secondary school"],
  "Colégio Diocesano de São José (6) (Secção Inglesa)": ["Secondary school"],
  "Colégio do Sagrado Coração de Jesus(Jardim de Infância)": ["Secondary school"],
  "Escola Oficial da Flora": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)": ["Secondary school"],
  "Escola São João de Brito (Nocturno)": ["Primary School", "Secondary school"],
  "Ensino Primário Recorrente": ["Secondary school"],
  "Escola Estrela do Mar (Nocturno)": ["Primary School", "Secondary school"],
  "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)": ["Kindergarten", "Primary School"],
  "Escola Luso-Chinesa Técnico-Profissional (Nocturno)": ["Kindergarten", "Primary School"],
  "Ensino Secundário Recorrente": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Secundária Nocturna Xin Hua": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Secundária Millennium": ["Secondary school"],
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)": ["Secondary school"],
  "Colégio Diocesano de São José (6) (Secção Nocturna)": ["Primary School"],
  "Escola Dom João Paulino": ["Kindergarten"],
  "Escola Fong Chong da Taipa (Sucursal)": ["Primary School"],
  "Escola Cáritas de Macau": ["Secondary school"],
  "Escola das Nações": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Luso-Chinesa da Taipa": ["Kindergarten", "Primary School"],
  "Escola Secundária Pui Va": ["Secondary school"],
  "Escola de Talentos Anexa à Escola Hou Kong": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Fong Chong da Taipa": ["Kindergarten", "Primary School"],
  "Escola Secundária Sam Yuk de Macau": ["Kindergarten"],
  "Escola Secundária Sam Yuk de Macau (Secção Inglesa)": ["Primary School"],
  "Escola de Aplicação Anexa à Universidade de Macau": ["Primary School", "Secondary school"],
  "Colégio Anglicano de Macau": ["Primary School", "Secondary school"],
  "Escola Internacional de Macau": ["Primary School", "Secondary school"],
  "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)": ["Secondary school"],
  "Escola Secundária Pui Va (Secção Primária e Infantil)": ["Secondary school"],
  "Secção Primària da Escola Pui Tou (Sucursal da Taipa)": ["Secondary school"],
  "Escola de São José de Ká Hó": ["Kindergarten"],
  "Escola Dom Luís Versíglia": ["Kindergarten", "Primary School", "Secondary school"],
  "Escola Oficial de Seac Pai Van": ["Special education", "Kindergarten", "Primary School", "Secondary school"],
  "Gerações - Escola Internacional": ["Kindergarten", "Primary School", "Secondary school"]
}

export const levelType = {
  "Kindergarten": ["k1", "k2", "k3"],
  "Primary School": ["p1", "p2", "p3", "p4", "p5", "p6"],
  "Secondary school": ["s1", "s2", "s3", "s4", "s5", "s6"],
  "Special education": ["Special education"]
}

export const schoolType = {
  "Escola Fong Chong da Taipa (Sucursal)": "Formal Education",
  "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)": "Adult Education",
  "Escola São João de Brito (Nocturno)": "Adult Education",
  "Ensino Primário Recorrente": "Adult Education",
  "Escola Estrela do Mar (Nocturno)": "Adult Education",
  "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)": "Adult Education",
  "Escola Luso-Chinesa Técnico-Profissional (Nocturno)": "Adult Education",
  "Ensino Secundário Recorrente": "Adult Education",
  "Escola Secundária Nocturna Xin Hua": "Adult Education",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)": "Adult Education",
  "Escola Secundária Millennium": "Adult Education",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)": "Adult Education",
  "Colégio Diocesano de São José (6) (Secção Nocturna)": "Adult Education",
  "Sheng Kung Hui Escola Choi Kou (Macau)": "Formal Education",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau": "Formal Education",
  "Escola Estrela do Mar (Rua do Padre António)": "Formal Education",
  "Escola da Associação Geral das Mulheres de Macau": "Formal Education",
  "Jardim de Infância Anexo à Escola Lou Hau": "Formal Education",
  "Escola Primária Anexa à Escola Lou Hau": "Formal Education",
  "Escola Secundária Lou Hau": "Formal Education",
  "Escola Há Ván Châm Vui": "Formal Education",
  "Escola Hou Kong (Pré-Primário)": "Formal Education",
  "Escola Hou Kong (Primário)": "Formal Education",
  "Escola Hou Kong": "Formal Education",
  "Instituto Salesiano da Imaculada Conceição": "Formal Education",
  "Escola Secundária Ilha Verde da Associação Comercial de Macau": "Formal Education",
  "Escola Kao Yip (Sucursal)": "Formal Education",
  "Escola Keang Peng (Secção Primária)": "Formal Education",
  "Escola Kwong Tai": "Formal Education",
  "Escola Lin Fong Pou Chai": "Formal Education",
  "Escola Ling Nam": "Formal Education",
  "Escola de Santa Madalena": "Formal Education",
  "Escola dos Moradores do Bairro do Patane": "Formal Education",
  "Escola Nossa Senhora de Fátima": "Formal Education",
  "Colégio Perpétuo Socorro Chan Sui Ki": "Formal Education",
  "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)": "Formal Education",
  "Escola Secundária Pui Ching": "Formal Education",
  "Escola Pui Tou": "Formal Education",
  "Escola Pui Tou (Sucursal da Praia Grande)": "Formal Education",
  "Colégio Mateus Ricci (Secundário)": "Formal Education",
  "Escola da Sagrada Família": "Formal Education",
  "Escola Santa Maria Mazzarello": "Formal Education",
  "Colégio de Santa Rosa de Lima - Secção Inglesa": "Formal Education",
  "Colégio de Santa Rosa de Lima - Secção Chinesa": "Formal Education",
  "Escola de Santa Teresa do Menino Jesus": "Formal Education",
  "Colégio Diocesano de São José (1)": "Formal Education",
  "Colégio Diocesano de São José (3)": "Formal Education",
  "Colégio Diocesano de São José (4)": "Formal Education",
  "Colégio Diocesano de São José 5 (Secção Chinesa)": "Formal Education",
  "Escola São Paulo": "Formal Education",
  "Escola Tak Meng": "Formal Education",
  "Escola Tong Nam": "Formal Education",
  "Escola Tong Sin Tong (Diurno)": "Formal Education",
  "Colégio Yuet Wah (Secção Chinesa)": "Formal Education",
  "Colégio Yuet Wah (Secção Inglesa)": "Formal Education",
  "Colégio do Sagrado Coração de Jesus": "Formal Education",
  "Colégio do Sagrado Coração de Jesus - Secção Inglesa": "Formal Education",
  "Escola Shá Lei Tau Cham Son": "Formal Education",
  "Escola Concórdia para Ensino Especial": "Formal Education",
  "Escola São João de Brito": "Formal Education",
  "Jardim Infantil da Cáritas": "Formal Education",
  "Escola Hói Fai": "Formal Education",
  "Centro de Educação Infantil Santo António": "Formal Education",
  "Escola Fukien": "Formal Education",
  "Escola Kai Chi": "Formal Education",
  "Jardim de Infância D.José da Costa Nunes": "Formal Education",
  "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung": "Formal Education",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes": "Formal Education",
  "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)": "Formal Education",
  "Colégio Diocesano de São José 5 (Secção Inglesa)": "Formal Education",
  "Escola Kwong Tai (Sucursal)": "Formal Education",
  "Escola dos Moradores de Macau(Avenida da Longevidade)": "Formal Education",
  "Escola Chong Tak de Macau": "Formal Education",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)": "Formal Education",
  "Jardim de Infância Anexo à Escola Tong Sin Tong": "Formal Education",
  "Escola Keang Peng( Secção Secundária)": "Formal Education",
  "Escola Sun Wah(Bairro do Hipodromo Norte, Rua de Serenidade)": "Formal Education",
  "Escola Pui Tou ( Sucursal da Secção Primária)": "Formal Education",
  "Escola Luso-Chinesa Técnico-Profissional": "Formal Education",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)": "Formal Education",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau": "Formal Education",
  "Escola Portuguesa de Macau": "Formal Education",
  "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)": "Formal Education",
  "Escola Tong Nam - Secundária": "Formal Education",
  "Escola Sun Wah(Avenida do Conselheiro Borja)": "Formal Education",
  "Escola dos Moradores de Macau(Avenida do Nordeste)": "Formal Education",
  "Escola Cham Son de Macau": "Formal Education",
  "Escola de Dança do Conservatório de Macau": "Formal Education",
  "Escola Estrela do Mar(Travessa do chunambeiro)": "Formal Education",
  "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)": "Formal Education",
  "Escola de Música do Conservatório de Macau": "Formal Education",
  "Escola Kao Yip": "Formal Education",
  "Seccao Infantil e Primaria do Colegio Mateus Ricci": "Formal Education",
  "Escola Oficial Zheng Guanying": "Formal Education",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)": "Formal Education",
  "Escola Sao Joao de Brito - Seccao Inglesa": "Formal Education",
  "Escola de Santa Madalena (Sucursal)": "Formal Education",
  "Colégio Diocesano de São José (2)": "Formal Education",
  "Colégio Diocesano de São José (6) (Secção Chinesa)": "Formal Education",
  "Colégio Diocesano de São José (6) (Secção Inglesa)": "Formal Education",
  "Colégio do Sagrado Coração de Jesus(Jardim de Infância)": "Formal Education",
  "Escola Oficial da Flora": "Formal Education",
  "Escola Dom João Paulino": "Formal Education",
  "Escola Cáritas de Macau": "Formal Education",
  "Escola das Nações": "Formal Education",
  "Escola Luso-Chinesa da Taipa": "Formal Education",
  "Escola Secundária Pui Va": "Formal Education",
  "Escola de Talentos Anexa à Escola Hou Kong": "Formal Education",
  "Escola Fong Chong da Taipa": "Formal Education",
  "Escola Secundária Sam Yuk de Macau": "Formal Education",
  "Escola Secundária Sam Yuk de Macau (Secção Inglesa)": "Formal Education",
  "Escola de Aplicação Anexa à Universidade de Macau": "Formal Education",
  "Colégio Anglicano de Macau": "Formal Education",
  "Escola Internacional de Macau": "Formal Education",
  "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)": "Formal Education",
  "Escola Secundária Pui Va (Secção Primária e Infantil)": "Formal Education",
  "Secção Primària da Escola Pui Tou (Sucursal da Taipa)": "Formal Education",
  "Escola de São José de Ká Hó": "Formal Education",
  "Escola Dom Luís Versíglia": "Formal Education",
  "Escola Oficial de Seac Pai Van": "Formal Education",
  "Gerações - Escola Internacional": "Formal Education",

}

