export const school_type = ["Formal Education", "Recurrent Education"]

export const region = ["Macau", "Taipa", "Coloane"]

export const classLevel = ["Kindergarten", "Primary School", "Secondary school"]


export const schoolName = {
  macau: [
    "Sheng Kung Hui Escola Choi Kou (Macau)",
    "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau",
    "Escola Estrela do Mar(Rua do Padre António)",
    "Escola da Associação Geral das Mulheres de Macau",
    "Jardim de Infância Anexo à Escola Lou Hau",
    "Escola Primária Anexa à Escola Lou Hau",
    "Escola Secundária Lou Hau",
    "Escola Há Ván Châm Vui",
    "Escola Hou Kong (Pré-Primário)",
    "Escola Hou Kong (Primário)",
    "Escola Hou Kong",
    "Instituto Salesiano da Imaculada Conceição",
    "Escola Secundária Ilha Verde da Associação Comercial de Macau",
    "Escola Kao Yip (Sucursal)",
    "Escola Keang Peng (Secção Primária)",
    "Escola Kwong Tai",
    "Escola Lin Fong Pou Chai",
    "Escola Ling Nam",
    "Escola de Santa Madalena",
    "Escola dos Moradores do Bairro do Patane",
    "Escola Nossa Senhora de Fátima",
    "Colégio Perpétuo Socorro Chan Sui Ki",
    "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)",
    "Escola Secundária Pui Ching",
    "Escola Pui Tou",
    "Escola Pui Tou (Sucursal da Praia Grande)",
    "Colégio Mateus Ricci (Secundário)",
    "Escola da Sagrada Família",
    "Escola Santa Maria Mazzarello",
    "Colégio de Santa Rosa de Lima - Secção Inglesa",
    "Colégio de Santa Rosa de Lima - Secção Chinesa",
    "Escola de Santa Teresa do Menino Jesus",
    "Colégio Diocesano de São José (1)",
    "Colégio Diocesano de São José (3)",
    "Colégio Diocesano de São José (4)",
    "Colégio Diocesano de São José 5 (Secção Chinesa)",
    "Escola São Paulo",
    "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)",
    "Escola Tak Meng",
    "Escola Tong Nam",
    "Escola Tong Sin Tong (Diurno)",
    "Colégio Yuet Wah (Secção Chinesa)",
    "Colégio Yuet Wah (Secção Inglesa)",
    "Colégio do Sagrado Coração de Jesus",
    "Colégio do Sagrado Coração de Jesus - Secção Inglesa",
    "Escola Shá Lei Tau Cham Son",
    "Escola Concórdia para Ensino Especial",
    "Escola São João de Brito",
    "Jardim Infantil da Cáritas",
    "Escola Hói Fai",
    "Centro de Educação Infantil Santo António",
    "Escola Fukien",
    "Escola Kai Chi",
    "Jardim de Infância D.José da Costa Nunes",
    "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung",
    "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes",
    "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)",
    "Colégio Diocesano de São José 5 (Secção Inglesa)",
    "Escola Kwong Tai (Sucursal)",
    "Escola dos Moradores de Macau(Avenida da Longevidade)",
    "Escola Chong Tak de Macau",
    "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)",
    "Jardim de Infância Anexo à Escola Tong Sin Tong",
    "Escola São João de Brito (Nocturno)",
    "Ensino Primário Recorrente",
    "Escola Estrela do Mar (Nocturno)",
    "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)",
    "Escola Keang Peng( Secção Secundária)",
    "Escola Sun Wah(Rua de Serenidade)",
    "Escola Pui Tou ( Sucursal da Secção Primária)",
    "Escola Luso-Chinesa Técnico-Profissional",
    "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)",
    "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau",
    "Escola Portuguesa de Macau",
    "Escola Luso-Chinesa Técnico-Profissional (Nocturno)",
    "Ensino Secundário Recorrente",
    "Escola Secundária Nocturna Xin Hua",
    "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)",
    "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)",
    "Escola Tong Nam - Secundária",
    "Escola Sun Wah(Avenida do Conselheiro Borja)",
    "Escola dos Moradores de Macau(Avenida do Nordeste)",
    "Escola Cham Son de Macau",
    "Escola Secundária Millennium",
    "Escola de Dança do Conservatório de Macau",
    "Escola Estrela do Mar(Travessa do chunambeiro)",
    "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)",
    "Escola de Música do Conservatório de Macau",
    "Escola Kao Yip",
    "Seccao Infantil e Primaria do Colegio Mateus Ricci",
    "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)",
    "Escola Oficial Zheng Guanying",
    "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)",
    "Escola Sao Joao de Brito - Seccao Inglesa",
    "Escola de Santa Madalena (Sucursal)",
    "Colégio Diocesano de São José (2)",
    "Colégio Diocesano de São José (6) (Secção Chinesa)",
    "Colégio Diocesano de São José (6) (Secção Inglesa)",
    "Colégio Diocesano de São José (6) (Secção Nocturna)",
    "Colégio do Sagrado Coração de Jesus(Jardim de Infância)",
    "Escola Oficial da Flora",
  ],
  taipa: [
    "Escola Dom João Paulino",
    "Escola Fong Chong da Taipa (Sucursal)",
    "Escola Cáritas de Macau",
    "Escola das Nações",
    "Escola Luso-Chinesa da Taipa",
    "Escola Secundária Pui Va",
    "Escola de Talentos Anexa à Escola Hou Kong",
    "Escola Fong Chong da Taipa",
    "Escola Secundária Sam Yuk de Macau",
    "Escola Secundária Sam Yuk de Macau (Secção Inglesa)",
    "Escola de Aplicação Anexa à Universidade de Macau",
    "Colégio Anglicano de Macau",
    "Escola Internacional de Macau",
    "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)",
    "Escola Secundária Pui Va (Secção Primária e Infantil)",
    "Secção Primària da Escola Pui Tou (Sucursal da Taipa)",
  ],
  colane: [
    "Escola de São José de Ká Hó",
    "Escola Dom Luís Versíglia",
    "Escola Oficial de Seac Pai Van",
    "Gerações - Escola Internacional",
  ],

}

export const schoolAddress = {
  "Sheng Kung Hui Escola Choi Kou (Macau)": "Rua Pedro Nolasco da Silva, no.53",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau": "Istmo de Ferreira do Amaral, no.40",
  "Escola Dom João Paulino": "Avenida Carlos da Maia, s/n",
  "Escola Estrela do Mar(Rua do Padre António)": "Rua do Padre António, no.36",
  "Escola da Associação Geral das Mulheres de Macau": "Avenida do Dr. Francisco Vieira Machado, n.362",
  "Jardim de Infância Anexo à Escola Lou Hau": "Avenida Marginal do Lam mau, no.588, Macau.",
  "Escola Primária Anexa à Escola Lou Hau": "Estrada do Repouso, no. 76A",
  "Escola Secundária Lou Hau": "Rua 2 do Bairro da Concórdia, no. 163",
  "Escola Fong Chong da Taipa (Sucursal)": "Rua do Delegado, s/n",
  "Escola Há Ván Châm Vui": "Rua da Praia do Manduco, nos. 46-48",
  "Escola Hou Kong (Pré-Primário)": "Estrada do Repouso, Nos. 73 e 75",
  "Escola Hou Kong (Primário)": "Rua Afonso de Albuquerque, nos. 25-27",
  "Escola Hou Kong": "Estrada da Ferreira do Amaral, no.3",
  "Instituto Salesiano da Imaculada Conceição": "Rua de S. Lourenço, no.16",
  "Escola Secundária Ilha Verde da Associação Comercial de Macau": "Avenida Conselheiro Borja, no.496",
  "Escola Kao Yip (Sucursal)": "Rua do Monte, nos. 4-6",
  "Escola Keang Peng (Secção Primária)": "Rua Francisco Xavier Pereira , no.128",
  "Escola Kwong Tai": "Rua de Fai Chi Kei, Habitação Social de Fai Chi Kei",
  "Escola Lin Fong Pou Chai": "Avenida do Almirante Lacerda, anexa ao Templo Lin Fong Pou Chai",
  "Escola Ling Nam": "Estrada dos Parses, no. 1",
  "Escola de Santa Madalena": "Rua Comandante João Belo, no. 28, Fai Chi Kei",
  "Escola dos Moradores do Bairro do Patane": "Rua da Palmeira, no. 99, r/c",
  "Escola Nossa Senhora de Fátima": "Rua da Missao de Fatima no. 61",
  "Colégio Perpétuo Socorro Chan Sui Ki": "Estrada da Vitória, no.28",
  "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)": "Travessa dos Bombeiros, no. 9G",
  "Escola Secundária Pui Ching": "Avenida Horta e Costa, no.7",
  "Escola Pui Tou": "Avenida do Dr. Rodrigo Rodrigues, no.263",
  "Escola Pui Tou (Sucursal da Praia Grande)": "Avenida da Praia Grande, no.779",
  "Colégio Mateus Ricci (Secundário)": "Travessa de São Paulo, no.1A",
  "Escola da Sagrada Família": "Rua de Bráz da Rosa, no. 15",
  "Escola Santa Maria Mazzarello": "Rua da Praia do Manduco, no. 103",
  "Colégio de Santa Rosa de Lima - Secção Inglesa": "Avenida Dr. Rodrigo Rodrigues, no. 367",
  "Colégio de Santa Rosa de Lima - Secção Chinesa": "Rua de Santa Clara, no. 21",
  "Escola de Santa Teresa do Menino Jesus": "Avenida do Conselheiro Borja, no. 568",
  "Colégio Diocesano de São José (1)": "Adro de S. Lázaro, no. 13",
  "Colégio Diocesano de São José (3)": "Travessa dos Anjos, no.43",
  "Colégio Diocesano de São José (4)": "Rua da Sé, no.17",
  "Colégio Diocesano de São José 5 (Secção Chinesa)": "Rua Central de Toi San, no.253 - 353",
  "Escola de São José de Ká Hó": "Aldeia de Ká Hó, Estrada de Nossa Senhora, no. 1151",
  "Escola São Paulo": "Rampa dos Cavaleiros, nos 12-14",
  "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)": "Avenida do Dr. Francisco Vieira Machado, no. 539",
  "Escola Tak Meng": "Rua do Mercado do Bairro Iao Hon, Edificio Lok Fu San Chun, 1 andar",
  "Escola Tong Nam": "Rua do Almirante Costa Cabral, no.138",
  "Escola Tong Sin Tong (Diurno)": "Rua Camilo Pessanha, no.64",
  "Colégio Yuet Wah (Secção Chinesa)": "Estrada da Vitoria, no.18",
  "Colégio Yuet Wah (Secção Inglesa)": "Estrada da Vitoria, no.18",
  "Colégio do Sagrado Coração de Jesus": "Avenida Coronel Mesquita, no.75,Macau",
  "Colégio do Sagrado Coração de Jesus - Secção Inglesa": "Avenida Ouvidor Arriaga, no.86",
  "Escola Shá Lei Tau Cham Son": "Rua Ribeira do Patane, no. 169-S",
  "Escola Concórdia para Ensino Especial": "Rua do Asilo, Bairro da Ilha Verde, No.35",
  "Escola Dom Luís Versíglia": "Rua Aldeia de Ká Hó",
  "Escola São João de Brito": "Rua de Pedro Coutinho, no. 118",
  "Escola Cáritas de Macau": "Rua Cidade de Lisboa, nos. 299, 371 e 387",
  "Jardim Infantil da Cáritas": "Avenida I de Maio Edf.Kam Hoi San Garden",
  "Escola das Nações": "Rua do Minho",
  "Escola Hói Fai": "Praça das Portas do Cerco, Edificio Jardim San Pou, 2 andar",
  "Centro de Educação Infantil Santo António": "Avenida Primeiro de Maio, Edifício Yu Wa r/c e 1.o andar",
  "Escola Fukien": "Rua de Lei Pou Chon, s/n",
  "Escola Kai Chi": "Rampa do Padre Vasconcelos",
  "Jardim de Infância D.José da Costa Nunes": "Avenida Sidónio Pais, s/n",
  "Escola Luso-Chinesa da Taipa": "Largo Governador Tamagnini Barbosa, S/N",
  "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung": "Estrada da Vitoria",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes": "Avenida de Sidónio Pais, s/n",
  "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)": "Estrada Ferreira do Amaral, no.6",
  "Colégio Diocesano de São José 5 (Secção Inglesa)": "Rua de Lei Pou Chon, no.320-358",
  "Escola Kwong Tai (Sucursal)": "Rua Nova Patane, no. 98, Edifício Luen San Square C.C. R/C A3",
  "Escola dos Moradores de Macau(Avenida da Longevidade)": "Avenida da Longevidade, no. 355",
  "Escola Chong Tak de Macau": "Rua dos Pescadores no. 90",
  "Escola Secundária Pui Va": "Rua Dois do Ocean Garden, no. 90, Edificio Ocean Garden",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)": "Avenida do Hipódromo, nos. 222-268, Wai Long Garden",
  "Escola de Talentos Anexa à Escola Hou Kong": "Rua Seng Tou",
  "Jardim de Infância Anexo à Escola Tong Sin Tong": "Rua Cidade de Santarem, No. 405, Edf Dynasty Garden, 2 andar",
  "Escola Fong Chong da Taipa": "Rua de Chaves, no.220",
  "Escola São João de Brito (Nocturno)": "Rua de Pedro Coutinho, no. 118",
  "Ensino Primário Recorrente": "Estrada da Vitoria",
  "Escola Secundária Sam Yuk de Macau": "Rua do Colegio, s/n",
  "Escola Estrela do Mar (Nocturno)": "Rua do Padre António, No. 36",
  "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)": "Rua Pedro Nolasco da Silva, no.53",
  "Escola Keang Peng( Secção Secundária)": "Avenida Hipódromo, no.389",
  "Escola Sun Wah(Rua de Serenidade)": "Bairro do Hipodromo Norte, Rua de Serenidade,s/n",
  "Escola Pui Tou ( Sucursal da Secção Primária)": "Rua de Formosa, No. 11",
  "Escola Secundária Sam Yuk de Macau (Secção Inglesa)": "Rua do Colegio, s/n",
  "Escola Luso-Chinesa Técnico-Profissional": "Rua Primeiro de Maio",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)": "Avenida de Sidónio Pais, s/n",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau": "Rua de Lai Pou Chon",
  "Escola Portuguesa de Macau": "Avenida Infante D. Henrique S/N",
  "Escola Luso-Chinesa Técnico-Profissional (Nocturno)": "Rua Primeiro de Maio",
  "Ensino Secundário Recorrente": "Avenida de Sidónio Pais, s/n",
  "Escola de Aplicação Anexa à Universidade de Macau": "Rua de Tai Lin BT34",
  "Escola Secundária Nocturna Xin Hua": "Avenda do Conselheiro Borja no 355, Ka Ying Court, 2 andar",
  "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)": "AVENIDA DR. FRANCISCO V MACHADO,No. 266",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)": "Avenida de Sidónio Pais, s/n",
  "Escola Tong Nam - Secundária": "Praca Luis de Camoes, Nos. 5-7",
  "Escola Sun Wah(Avenida do Conselheiro Borja)": "Avenida do Conselheiro Borja, no.355, Ka Ying Court, 2 andar",
  "Escola dos Moradores de Macau(Avenida do Nordeste)": "Avenida do Nordeste, no.109, Edif. Nam Ou, 1 e 2 andares",
  "Colégio Anglicano de Macau": "Avenida Padre Tomás Pereira, no,109-117",
  "Escola Internacional de Macau": "Avenida Wai Long, Universidade de Ciência e Tecnologia De Macau, Bloco K",
  "Escola Cham Son de Macau": "Rua Central da Areia Preta, No. 410",
  "Escola Secundária Millennium": "Avenida Sir Anders Ljungstedt, no. 238, China Civil Plaza, 8o., 9o. andares e 17o. andar G",
  "Escola de Dança do Conservatório de Macau": "Alameda Dr. Carlos D'Assumpcao No. 335-341, Hotline Building, 3 andar - NAPE",
  "Escola Estrela do Mar(Travessa do chunambeiro)": "Travessa do chunambeiro, nos.10-12",
  "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)": "Rua de Nam Keng 2a Fase do Edificio Nova taipa Garaden(Nova City) fracção D R/C do Bl VI e VIII",
  "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)": "Estrada Ferreira do Amaral, no.6",
  "Escola de Música do Conservatório de Macau": "Rua de Vo Long, 35",
  "Escola Kao Yip": "Avenida Xian Xing Hai, n.º 193, Macau",
  "Seccao Infantil e Primaria do Colegio Mateus Ricci": "Praca de Luis de Camoes n. 4 e Largo da Companhia n. 15",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)": "Rua de Lei Pou Chon",
  "Escola Oficial Zheng Guanying": "Rua Marginal do Canal das Hortas, s/n",
  "Escola Secundária Pui Va (Secção Primária e Infantil)": "Rua do Minho no. 93",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)": "Rua da Tranquilidade,no. 151, Jardim Wan Keng, R/C e 1?andar-B",
  "Secção Primària da Escola Pui Tou (Sucursal da Taipa)": "Avenida de Kwong Tung, n.os 775-827A e Rua do Minho, n.os 325-393, Edifício Hung Fat Garden, R/C, A-G, na Taipa",
  "Escola Sao Joao de Brito - Seccao Inglesa": "Rua de Pedro Coutinho, no. 118",
  "Escola de Santa Madalena (Sucursal)": "Largo da Companhia, no. 14",
  "Colégio Diocesano de São José (2)": "Rua da Prata, no. 1",
  "Colégio Diocesano de São José (6) (Secção Chinesa)": "Estrada Marginal da Ilha Verde, no.14-17",
  "Colégio Diocesano de São José (6) (Secção Inglesa)": "Estrada Marginal da Ilha Verde, no.14-17",
  "Colégio Diocesano de São José (6) (Secção Nocturna)": "Estrada Marginal da Ilha Verde, no.14-17",
  "Colégio do Sagrado Coração de Jesus(Jardim de Infância)": "Rua de Francisco Xavier Pereira, nos. 114-122",
  "Escola Oficial de Seac Pai Van": "Lote CN6a, Avenida Vale das Borboletas, Seac Pai Van",
  "Escola Oficial da Flora": "Travessa do Tunel, s/n, Jardim da Flora",
  "Gerações - Escola Internacional": "Aterro da Concórdia, junto à Estrada de Seac Pai Van, Lote 12a",
}

export const schoolLevel = {
  "Sheng Kung Hui Escola Choi Kou (Macau)": ["Kindergarten"],
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau": ["Primary School", "Secondary School"],
  "Escola Dom João Paulino": ["Kindergarten", "Primary School"],
  "Escola Estrela do Mar(Rua do Padre António)": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola da Associação Geral das Mulheres de Macau": ["Kindergarten", "Primary School"],
  "Jardim de Infância Anexo à Escola Lou Hau": ["Kindergarten"],
  "Escola Primária Anexa à Escola Lou Hau": ["Primary School"],
  "Escola Secundária Lou Hau": ["Secondary School"],
  "Escola Fong Chong da Taipa (Sucursal)": ["Kindergarten"],
  "Escola Há Ván Châm Vui": ["Kindergarten", "Primary School"],
  "Escola Hou Kong (Pré-Primário)": ["Kindergarten"],
  "Escola Hou Kong (Primário)": ["Kindergarten", "Primary School"],
  "Escola Hou Kong": ["Primary School", "Secondary School"],
  "Instituto Salesiano da Imaculada Conceição": ["Primary School", "Secondary School"],
  "Escola Secundária Ilha Verde da Associação Comercial de Macau": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Kao Yip (Sucursal)": ["Kindergarten", "Primary School"],
  "Escola Keang Peng (Secção Primária)": ["Kindergarten", "Primary School"],
  "Escola Kwong Tai": ["Secondary School"],
  "Escola Lin Fong Pou Chai": ["Kindergarten", "Primary School"],
  "Escola Ling Nam": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola de Santa Madalena": ["Kindergarten", "Primary School"],
  "Escola dos Moradores do Bairro do Patane": ["Kindergarten", "Primary School"],
  "Escola Nossa Senhora de Fátima": ["Kindergarten", "Primary School", "Secondary School"],
  "Colégio Perpétuo Socorro Chan Sui Ki": ["Primary School", "Secondary School"],
  "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)": ["Kindergarten", "Primary School"],
  "Escola Secundária Pui Ching": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Pui Tou": ["Secondary School"],
  "Escola Pui Tou (Sucursal da Praia Grande)": ["Kindergarten", "Primary School"],
  "Colégio Mateus Ricci (Secundário)": ["Primary School", "Secondary School"],
  "Escola da Sagrada Família": ["Kindergarten", "Primary School"],
  "Escola Santa Maria Mazzarello": ["Kindergarten", "Primary School"],
  "Colégio de Santa Rosa de Lima - Secção Inglesa": ["Primary School", "Secondary School"],
  "Colégio de Santa Rosa de Lima - Secção Chinesa": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola de Santa Teresa do Menino Jesus": ["Kindergarten", "Primary School"],
  "Colégio Diocesano de São José (1)": ["Kindergarten", "Primary School"],
  "Colégio Diocesano de São José (3)": ["Primary School", "Secondary School"],
  "Colégio Diocesano de São José (4)": ["Kindergarten"],
  "Colégio Diocesano de São José 5 (Secção Chinesa)": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola de São José de Ká Hó": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola São Paulo": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)": ["Secondary School"],
  "Escola Tak Meng": ["Kindergarten", "Primary School"],
  "Escola Tong Nam": ["Kindergarten", "Primary School"],
  "Escola Tong Sin Tong (Diurno)": ["Primary School", "Secondary School"],
  "Colégio Yuet Wah (Secção Chinesa)": ["Kindergarten", "Primary School", "Secondary School"],
  "Colégio Yuet Wah (Secção Inglesa)": ["Kindergarten", "Primary School", "Secondary School"],
  "Colégio do Sagrado Coração de Jesus": ["Kindergarten", "Primary School", "Secondary School"],
  "Colégio do Sagrado Coração de Jesus - Secção Inglesa": ["Primary School", "Secondary School"],
  "Escola Shá Lei Tau Cham Son": ["Kindergarten", "Primary School"],
  "Escola Concórdia para Ensino Especial": ["Special Education", "Kindergarten", "Primary School", "Secondary School"],
  "Escola Dom Luís Versíglia": ["Primary School", "Secondary School"],
  "Escola São João de Brito": ["Primary School", "Secondary School"],
  "Escola Cáritas de Macau": ["Special Education", "Kindergarten", "Primary School", "Secondary School"],
  "Jardim Infantil da Cáritas": ["Kindergarten"],
  "Escola das Nações": ["Special Education", "Kindergarten", "Primary School", "Secondary School"],
  "Escola Hói Fai": ["Kindergarten", "Primary School"],
  "Centro de Educação Infantil Santo António": ["Kindergarten"],
  "Escola Fukien": ["Kindergarten", "Primary School"],
  "Escola Kai Chi": ["Special Education", "Kindergarten"],
  "Jardim de Infância D.José da Costa Nunes": ["Special Education", "Kindergarten"],
  "Escola Luso-Chinesa da Taipa": ["Special Education", "Kindergarten", "Primary School"],
  "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung": ["Special Education", "Kindergarten", "Primary School"],
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes": ["Secondary School"],
  "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)": ["Primary School"],
  "Colégio Diocesano de São José 5 (Secção Inglesa)": ["Primary School", "Secondary School"],
  "Escola Kwong Tai (Sucursal)": ["Kindergarten", "Primary School"],
  "Escola dos Moradores de Macau(Avenida da Longevidade)": ["Secondary School"],
  "Escola Chong Tak de Macau": ["Kindergarten", "Primary School"],
  "Escola Secundária Pui Va": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)": ["Kindergarten"],
  "Escola de Talentos Anexa à Escola Hou Kong": ["Kindergarten", "Primary School", "Secondary School"],
  "Jardim de Infância Anexo à Escola Tong Sin Tong": ["Kindergarten"],
  "Escola Fong Chong da Taipa": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola São João de Brito (Nocturno)": ["Primary School", "Secondary School"],
  "Ensino Primário Recorrente": ["Primary School"],
  "Escola Secundária Sam Yuk de Macau": ["Primary School", "Secondary School"],
  "Escola Estrela do Mar (Nocturno)": ["Secondary School"],
  "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)": ["Secondary School"],
  "Escola Keang Peng( Secção Secundária)": ["Secondary School"],
  "Escola Sun Wah(Rua de Serenidade)": ["Secondary School"],
  "Escola Pui Tou ( Sucursal da Secção Primária)": ["Primary School"],
  "Escola Secundária Sam Yuk de Macau (Secção Inglesa)": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Luso-Chinesa Técnico-Profissional": ["Special Education", "Kindergarten", "Primary School", "Secondary School"],
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Portuguesa de Macau": ["Primary School", "Secondary School"],
  "Escola Luso-Chinesa Técnico-Profissional (Nocturno)": ["Secondary School"],
  "Ensino Secundário Recorrente": ["Secondary School"],
  "Escola de Aplicação Anexa à Universidade de Macau": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Secundária Nocturna Xin Hua": ["Secondary School"],
  "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)": ["Primary School", "Secondary School"],
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)": ["Secondary School"],
  "Escola Tong Nam - Secundária": ["Primary School", "Secondary School"],
  "Escola Sun Wah(Avenida do Conselheiro Borja)": ["Kindergarten", "Primary School"],
  "Escola dos Moradores de Macau(Avenida do Nordeste)": ["Kindergarten", "Primary School"],
  "Colégio Anglicano de Macau": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Internacional de Macau": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Cham Son de Macau": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Secundária Millennium": ["Secondary School"],
  "Escola de Dança do Conservatório de Macau": ["Secondary School"],
  "Escola Estrela do Mar(Travessa do chunambeiro)": ["Primary School"],
  "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)": ["Kindergarten"],
  "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)": ["Primary School"],
  "Escola de Música do Conservatório de Macau": ["Secondary School"],
  "Escola Kao Yip": ["Kindergarten", "Primary School", "Secondary School"],
  "Seccao Infantil e Primaria do Colegio Mateus Ricci": ["Kindergarten", "Primary School"],
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)": ["Secondary School"],
  "Escola Oficial Zheng Guanying": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Secundária Pui Va (Secção Primária e Infantil)": ["Kindergarten", "Primary School"],
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)": ["Kindergarten"],
  "Secção Primària da Escola Pui Tou (Sucursal da Taipa)": ["Primary School"],
  "Escola Sao Joao de Brito - Seccao Inglesa": ["Primary School", "Secondary School"],
  "Escola de Santa Madalena (Sucursal)": ["Primary School", "Secondary School"],
  "Colégio Diocesano de São José (2)": ["Primary School", "Secondary School"],
  "Colégio Diocesano de São José (6) (Secção Chinesa)": ["Secondary School"],
  "Colégio Diocesano de São José (6) (Secção Inglesa)": ["Secondary School"],
  "Colégio Diocesano de São José (6) (Secção Nocturna)": ["Secondary School"],
  "Colégio do Sagrado Coração de Jesus(Jardim de Infância)": ["Kindergarten"],
  "Escola Oficial de Seac Pai Van": ["Kindergarten", "Primary School", "Secondary School"],
  "Escola Oficial da Flora": ["Special Education", "Kindergarten", "Primary School", "Secondary School"],
  "Gerações - Escola Internacional": ["Kindergarten", "Primary School", "Secondary School"],
}

export const levelType = {
  "Kindergarten": ["k1", "k2", "k3"],
  "Primary School": ["p1", "p2", "p3", "p4", "p5", "p6"],
  "Secondary school": ["s1", "s2", "s3", "s4", "s5", "s6"],
  "Special education": ["Special education"]
}

export const schoolType = {
  "Sheng Kung Hui Escola Choi Kou (Macau)": "Formal Education",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau": "Formal Education",
  "Escola Dom João Paulino": "Formal Education",
  "Escola Estrela do Mar(Rua do Padre António)": "Formal Education",
  "Escola da Associação Geral das Mulheres de Macau": "Formal Education",
  "Jardim de Infância Anexo à Escola Lou Hau": "Formal Education",
  "Escola Primária Anexa à Escola Lou Hau": "Formal Education",
  "Escola Secundária Lou Hau": "Formal Education",
  "Escola Fong Chong da Taipa (Sucursal)": "Formal Education",
  "Escola Há Ván Châm Vui": "Formal Education",
  "Escola Hou Kong (Pré-Primário)": "Formal Education",
  "Escola Hou Kong (Primário)": "Formal Education",
  "Escola Hou Kong": "Formal Education",
  "Instituto Salesiano da Imaculada Conceição": "Formal Education",
  "Escola Secundária Ilha Verde da Associação Comercial de Macau": "Formal Education",
  "Escola Kao Yip (Sucursal)": "Formal Education",
  "Escola Keang Peng (Secção Primária)": "Formal Education",
  "Escola Kwong Tai": "Formal Education",
  "Escola Lin Fong Pou Chai": "Formal Education",
  "Escola Ling Nam": "Formal Education",
  "Escola de Santa Madalena": "Formal Education",
  "Escola dos Moradores do Bairro do Patane": "Formal Education",
  "Escola Nossa Senhora de Fátima": "Formal Education",
  "Colégio Perpétuo Socorro Chan Sui Ki": "Formal Education",
  "COLÉGIO DO PERPÉTUO SOCORRO CHAN SUI KI (SUC.)": "Formal Education",
  "Escola Secundária Pui Ching": "Formal Education",
  "Escola Pui Tou": "Formal Education",
  "Escola Pui Tou (Sucursal da Praia Grande)": "Formal Education",
  "Colégio Mateus Ricci (Secundário)": "Formal Education",
  "Escola da Sagrada Família": "Formal Education",
  "Escola Santa Maria Mazzarello": "Formal Education",
  "Colégio de Santa Rosa de Lima - Secção Inglesa": "Formal Education",
  "Colégio de Santa Rosa de Lima - Secção Chinesa": "Formal Education",
  "Escola de Santa Teresa do Menino Jesus": "Formal Education",
  "Colégio Diocesano de São José (1)": "Formal Education",
  "Colégio Diocesano de São José (3)": "Formal Education",
  "Colégio Diocesano de São José (4)": "Formal Education",
  "Colégio Diocesano de São José 5 (Secção Chinesa)": "Formal Education",
  "Escola de São José de Ká Hó": "Formal Education",
  "Escola São Paulo": "Formal Education",
  "Escola Seong Fan da Associação Comercial de Macau(Secção Nocturna)": "Formal Education",
  "Escola Tak Meng": "Formal Education",
  "Escola Tong Nam": "Formal Education",
  "Escola Tong Sin Tong (Diurno)": "Formal Education",
  "Colégio Yuet Wah (Secção Chinesa)": "Formal Education",
  "Colégio Yuet Wah (Secção Inglesa)": "Formal Education",
  "Colégio do Sagrado Coração de Jesus": "Formal Education",
  "Colégio do Sagrado Coração de Jesus - Secção Inglesa": "Formal Education",
  "Escola Shá Lei Tau Cham Son": "Formal Education",
  "Escola Concórdia para Ensino Especial": "Formal Education",
  "Escola Dom Luís Versíglia": "Formal Education",
  "Escola São João de Brito": "Formal Education",
  "Escola Cáritas de Macau": "Formal Education",
  "Jardim Infantil da Cáritas": "Formal Education",
  "Escola das Nações": "Formal Education",
  "Escola Hói Fai": "Formal Education",
  "Centro de Educação Infantil Santo António": "Formal Education",
  "Escola Fukien": "Formal Education",
  "Escola Kai Chi": "Formal Education",
  "Jardim de Infância D.José da Costa Nunes": "Formal Education",
  "Escola Luso-Chinesa da Taipa": "Formal Education",
  "Escola Primaria Oficial Luso-Chinesa Sir Robert Ho Tung": "Formal Education",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes": "Formal Education",
  "Colégio Dom Bosco (Yuet Wah) (Secção Chinesa)": "Formal Education",
  "Colégio Diocesano de São José 5 (Secção Inglesa)": "Formal Education",
  "Escola Kwong Tai (Sucursal)": "Formal Education",
  "Escola dos Moradores de Macau(Avenida da Longevidade)": "Formal Education",
  "Escola Chong Tak de Macau": "Formal Education",
  "Escola Secundária Pui Va": "Formal Education",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal)": "Formal Education",
  "Escola de Talentos Anexa à Escola Hou Kong": "Formal Education",
  "Jardim de Infância Anexo à Escola Tong Sin Tong": "Formal Education",
  "Escola Fong Chong da Taipa": "Formal Education",
  "Escola São João de Brito (Nocturno)": "Formal Education",
  "Ensino Primário Recorrente": "Formal Education",
  "Escola Secundária Sam Yuk de Macau": "Formal Education",
  "Escola Estrela do Mar (Nocturno)": "Formal Education",
  "Sheng Kung Hui Escola Choi Kou(Macau) (Nocturno)": "Formal Education",
  "Escola Keang Peng( Secção Secundária)": "Formal Education",
  "Escola Sun Wah(Rua de Serenidade)": "Formal Education",
  "Escola Pui Tou ( Sucursal da Secção Primária)": "Formal Education",
  "Escola Secundária Sam Yuk de Macau (Secção Inglesa)": "Formal Education",
  "Escola Luso-Chinesa Técnico-Profissional": "Formal Education",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Diurno-L.V.P.)": "Formal Education",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau": "Formal Education",
  "Escola Portuguesa de Macau": "Formal Education",
  "Escola Luso-Chinesa Técnico-Profissional (Nocturno)": "Formal Education",
  "Ensino Secundário Recorrente": "Formal Education",
  "Escola de Aplicação Anexa à Universidade de Macau": "Formal Education",
  "Escola Secundária Nocturna Xin Hua": "Formal Education",
  "Sheng Kung Hui Escola Choi Kou (Macau)(Sucursal)": "Formal Education",
  "Escola Secundária Luso-Chinesa de Luís Gonzaga Gomes (Curso Nocturno-Secção Portuguesa)": "Formal Education",
  "Escola Tong Nam - Secundária": "Formal Education",
  "Escola Sun Wah(Avenida do Conselheiro Borja)": "Formal Education",
  "Escola dos Moradores de Macau(Avenida do Nordeste)": "Formal Education",
  "Colégio Anglicano de Macau": "Formal Education",
  "Escola Internacional de Macau": "Formal Education",
  "Escola Cham Son de Macau": "Formal Education",
  "Escola Secundária Millennium": "Formal Education",
  "Escola de Dança do Conservatório de Macau": "Formal Education",
  "Escola Estrela do Mar(Travessa do chunambeiro)": "Formal Education",
  "Secção Infantil da Escola Pui Tou (Sucursal da Taipa)": "Formal Education",
  "Colégio Dom Bosco (Yuet Wah) (Secção Inglesa)": "Formal Education",
  "Escola de Música do Conservatório de Macau": "Formal Education",
  "Escola Kao Yip": "Formal Education",
  "Seccao Infantil e Primaria do Colegio Mateus Ricci": "Formal Education",
  "Escola Secundária Técnico-Profissional da Federação das Associações dos Operários de Macau(Nocturno)": "Formal Education",
  "Escola Oficial Zheng Guanying": "Formal Education",
  "Escola Secundária Pui Va (Secção Primária e Infantil)": "Formal Education",
  "Escola da Associação para Filhos e Irmãos dos Agricultores, em chinês Choi Nong Chi Tai Hoc Hau (Sucursal de Wan Keng)": "Formal Education",
  "Secção Primària da Escola Pui Tou (Sucursal da Taipa)": "Formal Education",
  "Escola Sao Joao de Brito - Seccao Inglesa": "Formal Education",
  "Escola de Santa Madalena (Sucursal)": "Formal Education",
  "Colégio Diocesano de São José (2)": "Formal Education",
  "Colégio Diocesano de São José (6) (Secção Chinesa)": "Formal Education",
  "Colégio Diocesano de São José (6) (Secção Inglesa)": "Formal Education",
  "Colégio Diocesano de São José (6) (Secção Nocturna)": "Formal Education",
  "Colégio do Sagrado Coração de Jesus(Jardim de Infância)": "Formal Education",
  "Escola Oficial de Seac Pai Van": "Formal Education",
  "Escola Oficial da Flora": "Formal Education",
  "Gerações - Escola Internacional": "Formal Education",
}

